# This is a basic workflow to help you get started with Actions

name: Deploy with gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: git remote set-url origin https://aryan02420:${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: npm run deploy -- -u "aryan02420 <aryan02420@github.com>"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
